
spring :
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRESQL_HOST}/plus_medical
    username: root
    password: ${POSTGRESQL_PASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true


  sql:
    init:
      mode: never
      continue-on-error: false
      schema-locations: classpath:/data/schema.sql
      data-locations: classpath:/data/data.sql


  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail:
        mime:
          charset: UTF
        smtp:
          writetimeout: 10000
          connectiontimeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host: ${VERIFY_EMAIL_HOST}

server:
  port: ${PORT}
  error:
    path: /user/error
    whitelabel:
      enabled: false

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}


cloudinary:
  cloud_name: dt6mlfety
  api_key: 181787623784263
  api_secret: icYbD9yECU8zuWRNEUkEHgyYRnY